### ISSUE TITLE
[FEAT] Category Service

### ISSUE THREAD

**Issue by evryhungry** [HandongRoot/Root_be#3]
## Issue

- PM이 일하래요.... 
- 특히 Category 하래요....

## ScreenShot

- 어떤 기능을 추가할 것인지 적어주세요

## To-do
- [x] 카테고리 생성
- [x] 카테고리 찾기 (검색)
- [x] 카테고리 전체 찾기 
- [x] 카테고리 이름 수정 기능
- [x] 카테고리 삭제 기능 (물어볼것? - 안에 contents 가 있으면 삭제를 못하게 막을 것인가? )
